name: Sync Translations with Crowdin

on:
    push:
        branches: [main]

jobs:
    synchronize-with-crowdin:
        runs-on: depot-ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: crowdin action
              uses: crowdin/github-action@v2
              with:
                  upload_sources: true
                  upload_translations: true
                  download_translations: true
                  localization_branch_name: l10n_crowdin
                  crowdin_branch_name: main
                  create_pull_request: true
                  pull_request_title: "chore(translations): update translations via Crowdin"
                  pull_request_body: "New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)"
                  pull_request_base_branch_name: "main"
                  pull_request_reviewers: kmendell
              env:
                  GITHUB_TOKEN: ${{ secrets.ARCANE_BOT_TOKEN }}
                  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
